These things don't work for samba mounted multimedia directories
Signed-off-by: John Schmidt <john@schmidthaus.rocks>

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -24,11 +24,10 @@ ynh_add_nginx_config
 #=================================================
 ynh_script_progression --message="Updating a configuration file..." --weight=2
 
-if [ "$path" != "/" ]
-then
-	path_less="$path/"
+if [ "$path" != "/" ]; then
+    path_less="$path/"
 else
-	path_less="$path"
+    path_less="$path"
 fi
 
 _save_and_revert_rpc_password_hash_to_password
@@ -38,37 +37,36 @@ ynh_add_config --template="../conf/settings.json" --destination="$SETTINGS_FILE"
 chmod 400 "$SETTINGS_FILE"
 chown debian-transmission:debian-transmission "$SETTINGS_FILE"
 
-if [ -e /proc/sys/net/core/rmem_max ]
-then
-	ynh_add_config --template="../conf/90-transmission.conf" --destination="/etc/sysctl.d/90-transmission.conf"
+if [ -e /proc/sys/net/core/rmem_max ]; then
+    ynh_add_config --template="../conf/90-transmission.conf" --destination="/etc/sysctl.d/90-transmission.conf"
 
-	chmod 400 "/etc/sysctl.d/90-transmission.conf"
-	chown debian-transmission:debian-transmission "/etc/sysctl.d/90-transmission.conf"
+    chmod 400 "/etc/sysctl.d/90-transmission.conf"
+    chown debian-transmission:debian-transmission "/etc/sysctl.d/90-transmission.conf"
 
-	sysctl --load=/etc/sysctl.d/90-transmission.conf
+    sysctl --load=/etc/sysctl.d/90-transmission.conf
 fi
 
 #=================================================
 # YUNOHOST MULTIMEDIA INTEGRATION
 #=================================================
-ynh_script_progression --message="Adding multimedia directories..." --weight=3
-
-# Remove possibly dangling symlinks created before the /home/yunohost.transmission -> /home/yunohost.app/transmission transition
-# Use rm because ynh_secure_remove fails on dangling symlinks, see https://github.com/YunoHost/issues/issues/2253...
-rm "$MEDIA_DIRECTORY/share/Torrents" || true
-rm "$MEDIA_DIRECTORY/share/Torrent to download" || true
-
-ynh_multimedia_build_main_dir
-
-# Set rights on transmission directory (parent need to be readable by other, and progress need to be writable by multimedia. Because files will move)
-ynh_multimedia_addfolder --source_dir="$data_dir" --dest_dir="share/Torrents"
-
-# And share completed directory
-ynh_multimedia_addfolder --source_dir="$data_dir/completed" --dest_dir="share/Torrents"
-
-# Share also watched directory, to allow to use it easily
-ynh_multimedia_addfolder --source_dir="$data_dir/watched" --dest_dir="share/Torrent to download"
-
+# ynh_script_progression --message="Adding multimedia directories..." --weight=3
+#
+# # Remove possibly dangling symlinks created before the /home/yunohost.transmission -> /home/yunohost.app/transmission transition
+# # Use rm because ynh_secure_remove fails on dangling symlinks, see https://github.com/YunoHost/issues/issues/2253...
+# rm "$MEDIA_DIRECTORY/share/Torrents" || true
+# rm "$MEDIA_DIRECTORY/share/Torrent to download" || true
+#
+# ynh_multimedia_build_main_dir
+#
+# # Set rights on transmission directory (parent need to be readable by other, and progress need to be writable by multimedia. Because files will move)
+# ynh_multimedia_addfolder --source_dir="$data_dir" --dest_dir="share/Torrents"
+#
+# # And share completed directory
+# ynh_multimedia_addfolder --source_dir="$data_dir/completed" --dest_dir="share/Torrents"
+#
+# # Share also watched directory, to allow to use it easily
+# ynh_multimedia_addfolder --source_dir="$data_dir/watched" --dest_dir="share/Torrent to download"
+#
 #=================================================
 # PATCH SOURCE TO ADD A DOWNLOAD BUTTON
 #=================================================
@@ -78,13 +76,13 @@ _add_download_button
 #=================================================
 # SET DATA DIRECTORY PERMISSIONS
 #=================================================
-ynh_script_progression --message="Set data directory permissions..." --weight=1
-
-chmod -R 775 $data_dir
-chmod -R 775 $data_dir/watched
-chown -R debian-transmission:www-data "$data_dir"
-chown -R debian-transmission: $data_dir/{progress,watched}
-
+# ynh_script_progression --message="Set data directory permissions..." --weight=1
+#
+# chmod -R 775 $data_dir
+# chmod -R 775 $data_dir/watched
+# chown -R debian-transmission:www-data "$data_dir"
+# chown -R debian-transmission: $data_dir/{progress,watched}
+#
 #=================================================
 # INTEGRATE SERVICE IN YUNOHOST
 #=================================================
